# Dockerfile.agent
FROM jenkins/inbound-agent:latest-jdk17

USER root

# Install netcat-openbsd (because "netcat" fails now in Debian images)
RUN apt-get update \
    && apt-get install -y --no-install-recommends netcat-openbsd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER jenkins
