version: "3.8"

services:
  jenkins-master:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-controller
    ports:
      - "8888:8080" # Jenkins web
      - "50000:50000" # JNLP agent port
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  jenkins-agent-1:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins-agent-01
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME01}
      - JENKINS_SECRET=${JENKINS_SECRET_AGENT01}
    entrypoint:
      - sh
      - -c
      - |
        while ! nc -z jenkins-master 8080; do echo Waiting for Jenkins master...; sleep 5; done;
        echo 'Sleeping extra 30 sec to allow Jenkins plugins to load...'; sleep 30;
        java -jar /usr/share/jenkins/agent.jar -url "$JENKINS_URL" -secret "$JENKINS_SECRET" -name "$JENKINS_AGENT_NAME" -webSocket -workDir /home/jenkins/agent
    networks:
      - jenkins-net

  jenkins-agent-2:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: jenkins-agent-02
    depends_on:
      - jenkins-master
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME02}
      - JENKINS_SECRET=${JENKINS_SECRET_AGENT02}
    entrypoint:
      - sh
      - -c
      - |
        while ! nc -z jenkins-master 8080; do echo Waiting for Jenkins master...; sleep 5; done;
        echo 'Sleeping extra 30 sec to allow Jenkins plugins to load...'; sleep 30;
        java -jar /usr/share/jenkins/agent.jar -url "$JENKINS_URL" -secret "$JENKINS_SECRET" -name "$JENKINS_AGENT_NAME" -webSocket -workDir /home/jenkins/agent
    networks:
      - jenkins-net

volumes:
  jenkins_home:
networks:
  jenkins-net:
    driver: bridge
