version: "3.8"

services:
  jenkins-master:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-controller
    ports:
      - "8888:8080" # Jenkins web
      - "50000:50000" # JNLP agent port
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins-net

  jenkins-agent-1:
    build:
      context: .
      dockerfile: Dockerfile.agent-with-compose
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: jenkins-agent-01
    depends_on:
      jenkins-master:
        condition: service_started
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME01}
      - JENKINS_SECRET=${JENKINS_SECRET_AGENT01}
    entrypoint:
      - java
      - -jar
      - /usr/share/jenkins/agent.jar
      - -url
      - "$JENKINS_URL"
      - -secret
      - "$JENKINS_SECRET_AGENT01"
      - -name
      - "$JENKINS_AGENT_NAME01"
      - -workDir
      - "/home/jenkins/agent"
    networks:
      - jenkins-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jenkins-agent-2:
    build:
      context: .
      dockerfile: Dockerfile.agent-with-compose
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: jenkins-agent-02
    depends_on:
      jenkins-master:
        condition: service_started
    environment:
      - JENKINS_URL=${JENKINS_URL}
      - JENKINS_AGENT_NAME=${JENKINS_AGENT_NAME02}
      - JENKINS_SECRET=${JENKINS_SECRET_AGENT02}
    entrypoint:
      - java
      - -jar
      - /usr/share/jenkins/agent.jar
      - -url
      - "$JENKINS_URL"
      - -secret
      - "$JENKINS_SECRET_AGENT02"
      - -name
      - "$JENKINS_AGENT_NAME02"
      - -workDir
      - "/home/jenkins/agent"
    networks:
      - jenkins-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Enables docker CLI in agent

volumes:
  jenkins_home:
networks:
  jenkins-net:
    driver: bridge
